export { default as About } from './About'
export { default as Images } from './Images'
export { default as HomeLayout } from './HomeLayout'
export { default as Landing } from './Landing'
export { default as NewsLatter } from './NewsLatter'
export { default as Error } from './Error'
export { default as SinglePageError } from './SinglePageError'
