export { default as About } from './About'
export { default as Book } from './Book'
export { default as Error } from './Error'
export { default as HomeLayout } from './HomeLayout'
export { default as Landing } from './Landing'
export { default as NewsLatter } from './NewsLatter'
